// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using habitos_app.Web.Data;

#nullable disable

namespace habitos_app.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("habitos_app.Web.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");
                });

            modelBuilder.Entity("habitos_app.Web.Models.AdminUser", b =>
                {
                    b.HasBaseType("habitos_app.Web.Models.User");

                    b.HasDiscriminator().HasValue("AdminUser");
                });

            modelBuilder.Entity("habitos_app.Web.Models.HealthProfessional", b =>
                {
                    b.HasBaseType("habitos_app.Web.Models.User");

                    b.Property<int>("ProfessionalLicenseNumber")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("HealthProfessional");
                });

            modelBuilder.Entity("habitos_app.Web.Models.RegularUser", b =>
                {
                    b.HasBaseType("habitos_app.Web.Models.User");

                    b.HasDiscriminator().HasValue("RegularUser");
                });
#pragma warning restore 612, 618
        }
    }
}
